port killms_data to mpiManager
but kMS.py needs to be patched for the numpy version 1.25.2
Traceback (most recent call last):
  File "/install/linux-zen3/py-killms-git.880ac1c0ad20382482b3330b5a923515bd30cb3b_custom-lkp54p63fi2px37dgk2zbfmey6hzw23y/bin/kMS.py", line 1589, in <module>
    main(OP=OP,MSName=MSName)
  File "/install/linux-zen3/py-killms-git.880ac1c0ad20382482b3330b5a923515bd30cb3b_custom-lkp54p63fi2px37dgk2zbfmey6hzw23y/bin/kMS.py", line 634, in main
    VS=ClassVisServer.ClassVisServer(options.MSName,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/install/linux-zen3/py-killms-git.880ac1c0ad20382482b3330b5a923515bd30cb3b_custom-lkp54p63fi2px37dgk2zbfmey6hzw23y/lib/python3.11/site-packages/killMS/Data/ClassVisServer.py", line 127, in __init__
    self.Init()
  File "/install/linux-zen3/py-killms-git.880ac1c0ad20382482b3330b5a923515bd30cb3b_custom-lkp54p63fi2px37dgk2zbfmey6hzw23y/lib/python3.11/site-packages/killMS/Data/ClassVisServer.py", line 193, in Init
    MS=ClassMS(self.MSName,
       ^^^^^^^^^^^^^^^^^^^^
  File "/install/linux-zen3/py-killms-git.880ac1c0ad20382482b3330b5a923515bd30cb3b_custom-lkp54p63fi2px37dgk2zbfmey6hzw23y/lib/python3.11/site-packages/killMS/Data/ClassMS.py", line 79, in __init__
    self.ReadMSInfo(MSname,DoPrint=DoPrint)
  File "/install/linux-zen3/py-killms-git.880ac1c0ad20382482b3330b5a923515bd30cb3b_custom-lkp54p63fi2px37dgk2zbfmey6hzw23y/lib/python3.11/site-packages/killMS/Data/ClassMS.py", line 886, in ReadMSInfo
    self.StrRA  = rad2hmsdms(self.rarad,Type="ra").replace(" ",":")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/install/linux-zen3/py-killms-git.880ac1c0ad20382482b3330b5a923515bd30cb3b_custom-lkp54p63fi2px37dgk2zbfmey6hzw23y/lib/python3.11/site-packages/killMS/Other/rad2hmsdms.py", line 41, in rad2hmsdms
    degd=np.int(deg)
         ^^^^^^
  File "/install/linux-zen3/py-numpy-1.25.2-k2c4kimxyrncsu52reb5xdwu7ospnjb6/lib/python3.11/site-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> /install/linux-zen3/py-numpy-1.25.2-k2c4kimxyrncsu52reb5xdwu7ospnjb6/lib/python3.11/site-packages/numpy/__init__.py(319)__getattr__()